package fr.ufrv.interfaces;

import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import org.apache.lucene.queryparser.classic.ParseException;

import com.hp.hpl.jena.rdf.model.Statement;

import fr.ufrv.traitement.Lucene;
import fr.ufrv.traitement.RDF;
import fr.ufrv.traitement.RDFManager;

/**
*
* @author CHAABANI Oussama
*/

public class Interf_rdf extends javax.swing.JFrame {
	
	private DefaultTableModel model = new DefaultTableModel(); 
	private Lucene lucene;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form interface_rdf
	 */
	public Interf_rdf() {
		initComponents();
		lucene = new Lucene();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		chemin = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		matable = new javax.swing.JTable(model);
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		cmd_search = new javax.swing.JButton();
		cmd_quit = new javax.swing.JButton();
		cmd_si = new javax.swing.JButton();
		txt_search = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setLayout(null);

		chemin.setBackground(new java.awt.Color(204, 204, 204));
		chemin.setToolTipText("chemin sur dique");
		chemin.setEnabled(false);
		jPanel1.add(chemin);
		chemin.setBounds(510, 60, 450, 40);
		model.addColumn("Ressource");
		model.addColumn("Prédicat");
		model.addColumn("Objet");

		//matable.setModel(new javax.swing.table.DefaultTableModel(
		//new Object [][] {

		//},
		//new String [] {

		//}
		//));

		jScrollPane1.setViewportView(matable);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(20, 170, 940, 450);
		jPanel1.add(jSeparator1);
		jSeparator1.setBounds(20, 160, 940, 20);
		jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
		jPanel1.add(jSeparator2);
		jSeparator2.setBounds(490, 0, 10, 160);

		cmd_search.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
		cmd_search.setText("RDF PATH");
		cmd_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmd_searchActionPerformed(evt);
			}
		});
		jPanel1.add(cmd_search);
		cmd_search.setBounds(100, 60, 170, 40);

		cmd_quit.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
		cmd_quit.setText("EXIT");
		cmd_quit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmd_quitActionPerformed(evt);
			}
		});
		jPanel1.add(cmd_quit);
		cmd_quit.setBounds(290, 60, 170, 40);

		cmd_si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-silver-icon.png"))); // NOI18N
		cmd_si.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmd_siActionPerformed(evt);
			}
		});
		jPanel1.add(cmd_si);
		cmd_si.setBounds(900, 110, 60, 40);

		jPanel1.add(txt_search);
		txt_search.setBounds(509, 110, 390, 40);

		jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
		jLabel1.setText("FICHIER:");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(510, 20, 120, 30);

		jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
		jLabel3.setText("COMMANDES:");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(20, 20, 120, 30);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wallpaper658185.jpg"))); // NOI18N
		jPanel1.add(jLabel2);
		jLabel2.setBounds(0, 0, 980, 640);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
				);

		setSize(new java.awt.Dimension(995, 679));
		setLocationRelativeTo(null);
	} // </editor-fold>                        

	private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {                                           

		JFileChooser chooser=new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter("RDF", "rdf");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(null);
		File f=chooser.getSelectedFile();
		String filename=f.getAbsolutePath();
		chemin.setText(filename);

		if(returnVal == JFileChooser.APPROVE_OPTION) {
			System.out.println("You chose to open this file: " + chooser.getSelectedFile().getPath());
			RDF rdf = new RDF(filename);
			RDFManager rdfManager= new RDFManager(rdf);

			int result = rdfManager.readFileRDF(f);
			if(result == 1 )
			{
				while (model.getRowCount()!=0)
					model.removeRow(0);
				//succès
				try {
					lucene.index(rdfManager.getTriplets());
				} catch (IOException | ParseException e) {
					e.printStackTrace();
				}

				for(Statement triplet : rdfManager.getTriplets())
				{
					model.addRow(new Object[]{triplet.getSubject().toString(), triplet.getPredicate().getLocalName().toString(),triplet.getObject().toString()});
				}
				
			}
			else {}//échec

		}
	}

	private void cmd_quitActionPerformed(java.awt.event.ActionEvent evt) {                                         

		int p= JOptionPane.showConfirmDialog(null, "Do you really want to quit","Quit",JOptionPane.YES_NO_OPTION);
		if(p==0){
			System.exit(0);
		}        
	}  

	private void cmd_siActionPerformed(java.awt.event.ActionEvent evt)  
	{
		String req=txt_search.getText();
		try {
			while (model.getRowCount()!=0)
				model.removeRow(0);
			
			Object[][]result = lucene.Search(req);
			for(int i=0; i<result.length;i++)
				model.addRow( result[i]);
		} catch (ParseException e) {

			e.printStackTrace();
		} catch (IOException e) {

			e.printStackTrace();
		}
		
	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interf_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interf_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interf_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interf_rdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interf_rdf().setVisible(true);

			}
		});
	}
	// Variables declaration - do not modify                     
	private javax.swing.JTextField chemin;
	private javax.swing.JButton cmd_quit;
	private javax.swing.JButton cmd_search;
	private javax.swing.JButton cmd_si;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTable matable;
	private javax.swing.JTextField txt_search;
	// End of variables declaration      
}
